Repository hmcts/et-pet-et1, pull requests merged in 2024-06, with the labels that each got.

#1634 Rst 6694
  Gemfile
  Gemfile.lock
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et1-pr-1634

#1635 (RST-6695) Increased startup timeout for running migrations
  charts/et-pet-et1/Chart.yaml
  charts/et-pet-et1/values.yaml
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et1-pr-1635

#1637 RST-6338 - update crown logo
  Gemfile
  Gemfile.lock
  app/views/layouts/moj_template.html.erb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et1-pr-1637
