Repository hmcts/et-pet-et1, pull requests merged in 2024-03, with the labels that each got.

#1613 (RST-6198) Allow forward slashes in addresses
  app/validators/special_character_validator.rb
  spec/validators/special_character_validator_spec.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et1-pr-1613

#1617 (RST-6322) ET1 Rails upgrade
  Gemfile
  Gemfile.lock
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et1-pr-1617

#1618 (RST-6321) Slow db query
  app/controllers/application_controller.rb
  db/migrate/20240320062552_add_indexes_to_addresses.rb
  db/schema.rb
  spec/controllers/timeout_sessions_controller_spec.rb
Labels: ns:et-pet, prd:et-pet, enable_keep_helm, rel:et-pet-et1-pr-1618

#1620 Dummy change to readme to force build
  README.md
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et1-pr-1620

#1616 RST-6017 - average hours per week validations
  app/forms/employment_form.rb
  config/locales/en/et1/active_model.cy.yml
  config/locales/en/et1/active_model.en.yml
  spec/forms/employment_form_spec.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-et1-pr-1616
